server:
  port: 38080
  shutdown: graceful

spring:
  application:
    name: financePP
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/financepp
    username: root
    password: abctod
  thymeleaf:
    cache: false